name       : hunspell-el
version    : 0.9
release    : 4
source     :
    - http://elspell.math.upatras.gr/files/ooffice/el_GR-0.9.zip : 638984ed883a313ee1633bfe87ba6260b4c7771f22c1a0113d3d49138be8eead
license    : GPL-2.0-only
component  : office.spelling
summary    : Greek hunspell dictionaries
description: |
    Greek hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    install -Ddm00755 $installdir/usr/share/hunspell
    install -m00644 el_GR.dic el_GR.aff $installdir/usr/share/hunspell
